// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.actor.getProfiles

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// AlphaActorGetProfiles_Output is the output of a fm.teal.alpha.actor.getProfiles call.
type AlphaActorGetProfiles_Output struct {
	Actors []*AlphaActorDefs_MiniProfileView `json:"actors" cborgen:"actors"`
}

// AlphaActorGetProfiles calls the XRPC method "fm.teal.alpha.actor.getProfiles".
//
// actors: Array of actor DIDs
func AlphaActorGetProfiles(ctx context.Context, c *xrpc.Client, actors []string) (*AlphaActorGetProfiles_Output, error) {
	var out AlphaActorGetProfiles_Output

	params := map[string]interface{}{
		"actors": actors,
	}
	if err := c.Do(ctx, xrpc.Query, "", "fm.teal.alpha.actor.getProfiles", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
