// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.actor.searchActors

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// AlphaActorSearchActors_Output is the output of a fm.teal.alpha.actor.searchActors call.
type AlphaActorSearchActors_Output struct {
	Actors []*AlphaActorDefs_MiniProfileView `json:"actors" cborgen:"actors"`
	// cursor: Cursor for pagination
	Cursor *string `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
}

// AlphaActorSearchActors calls the XRPC method "fm.teal.alpha.actor.searchActors".
//
// cursor: Cursor for pagination
// limit: The maximum number of actors to return
// q: The search query
func AlphaActorSearchActors(ctx context.Context, c *xrpc.Client, cursor string, limit int64, q string) (*AlphaActorSearchActors_Output, error) {
	var out AlphaActorSearchActors_Output

	params := map[string]interface{}{
		"cursor": cursor,
		"limit":  limit,
		"q":      q,
	}
	if err := c.Do(ctx, xrpc.Query, "", "fm.teal.alpha.actor.searchActors", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
