// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.actor.defs

import (
	appbskytypes "github.com/bluesky-social/indigo/api/bsky"
)

// AlphaActorDefs_MiniProfileView is a "miniProfileView" in the fm.teal.alpha.actor.defs schema.
type AlphaActorDefs_MiniProfileView struct {
	// avatar: IPLD of the avatar
	Avatar *string `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// did: The decentralized identifier of the actor
	Did         *string `json:"did,omitempty" cborgen:"did,omitempty"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Handle      *string `json:"handle,omitempty" cborgen:"handle,omitempty"`
}

// AlphaActorDefs_ProfileView is a "profileView" in the fm.teal.alpha.actor.defs schema.
type AlphaActorDefs_ProfileView struct {
	// avatar: IPLD of the avatar
	Avatar *string `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// banner: IPLD of the banner image
	Banner    *string `json:"banner,omitempty" cborgen:"banner,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// description: Free-form profile description text.
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	// descriptionFacets: Annotations of text in the profile description (mentions, URLs, hashtags, etc). May be changed to another (backwards compatible) lexicon.
	DescriptionFacets []*appbskytypes.RichtextFacet `json:"descriptionFacets,omitempty" cborgen:"descriptionFacets,omitempty"`
	// did: The decentralized identifier of the actor
	Did         *string `json:"did,omitempty" cborgen:"did,omitempty"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	// featuredItem: The user's most recent item featured on their profile.
	FeaturedItem *AlphaActorProfile_FeaturedItem `json:"featuredItem,omitempty" cborgen:"featuredItem,omitempty"`
}
