// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.feed.getActorFeed

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// AlphaFeedGetActorFeed_Output is the output of a fm.teal.alpha.feed.getActorFeed call.
type AlphaFeedGetActorFeed_Output struct {
	Plays []*AlphaFeedDefs_PlayView `json:"plays" cborgen:"plays"`
}

// AlphaFeedGetActorFeed calls the XRPC method "fm.teal.alpha.feed.getActorFeed".
//
// authorDID: The author's DID for the play
// cursor: The cursor to start the query from
// limit: The upper limit of tracks to get per request. Default is 20, max is 50.
func AlphaFeedGetActorFeed(ctx context.Context, c *xrpc.Client, authorDID string, cursor string, limit int64) (*AlphaFeedGetActorFeed_Output, error) {
	var out AlphaFeedGetActorFeed_Output

	params := map[string]interface{}{
		"authorDID": authorDID,
		"cursor":    cursor,
		"limit":     limit,
	}
	if err := c.Do(ctx, xrpc.Query, "", "fm.teal.alpha.feed.getActorFeed", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
