// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.feed.play

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("fm.teal.alpha.feed.play", &AlphaFeedPlay{})
} //
// RECORDTYPE: AlphaFeedPlay
type AlphaFeedPlay struct {
	LexiconTypeID string `json:"$type,const=fm.teal.alpha.feed.play" cborgen:"$type,const=fm.teal.alpha.feed.play"`
	// artistMbIds: Array of Musicbrainz artist IDs
	ArtistMbIds []string `json:"artistMbIds,omitempty" cborgen:"artistMbIds,omitempty"`
	// artistNames: Array of artist names in order of original appearance.
	ArtistNames []string `json:"artistNames" cborgen:"artistNames"`
	// duration: The length of the track in seconds
	Duration *int64 `json:"duration,omitempty" cborgen:"duration,omitempty"`
	// isrc: The ISRC code associated with the recording
	Isrc *string `json:"isrc,omitempty" cborgen:"isrc,omitempty"`
	// musicServiceBaseDomain: The base domain of the music service. e.g. music.apple.com, tidal.com, spotify.com. Defaults to 'local' if unavailable or not provided.
	MusicServiceBaseDomain *string `json:"musicServiceBaseDomain,omitempty" cborgen:"musicServiceBaseDomain,omitempty"`
	// originUrl: The URL associated with this track
	OriginUrl *string `json:"originUrl,omitempty" cborgen:"originUrl,omitempty"`
	// playedTime: The unix timestamp of when the track was played
	PlayedTime *string `json:"playedTime,omitempty" cborgen:"playedTime,omitempty"`
	// recordingMbId: The Musicbrainz recording ID of the track
	RecordingMbId *string `json:"recordingMbId,omitempty" cborgen:"recordingMbId,omitempty"`
	// releaseMbId: The Musicbrainz release ID
	ReleaseMbId *string `json:"releaseMbId,omitempty" cborgen:"releaseMbId,omitempty"`
	// releaseName: The name of the release/album
	ReleaseName *string `json:"releaseName,omitempty" cborgen:"releaseName,omitempty"`
	// submissionClientAgent: A metadata string specifying the user agent where the format is `<app-identifier>/<version> (<kernel/OS-base>; <platform/OS-version>; <device-model>)`. If string is provided, only `app-identifier` and `version` are required. `app-identifier` is recommended to be in reverse dns format. Defaults to 'manual/unknown' if unavailable or not provided.
	SubmissionClientAgent *string `json:"submissionClientAgent,omitempty" cborgen:"submissionClientAgent,omitempty"`
	// trackMbId: The Musicbrainz ID of the track
	TrackMbId *string `json:"trackMbId,omitempty" cborgen:"trackMbId,omitempty"`
	// trackName: The name of the track
	TrackName string `json:"trackName" cborgen:"trackName"`
}
