// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.actor.getProfile

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// ActorGetProfile_Output is the output of a fm.teal.actor.getProfile call.
type ActorGetProfile_Output struct {
	Actor *ActorDefs_ProfileView `json:"actor" cborgen:"actor"`
}

// ActorGetProfile calls the XRPC method "fm.teal.actor.getProfile".
//
// actor: The author's DID
func ActorGetProfile(ctx context.Context, c util.LexClient, actor string) (*ActorGetProfile_Output, error) {
	var out ActorGetProfile_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.actor.getProfile", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
