// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.actor.getProfiles

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// ActorGetProfiles_Output is the output of a fm.teal.actor.getProfiles call.
type ActorGetProfiles_Output struct {
	Actors []*ActorDefs_MiniProfileView `json:"actors" cborgen:"actors"`
}

// ActorGetProfiles calls the XRPC method "fm.teal.actor.getProfiles".
//
// actors: Array of actor DIDs
func ActorGetProfiles(ctx context.Context, c util.LexClient, actors []string) (*ActorGetProfiles_Output, error) {
	var out ActorGetProfiles_Output

	params := map[string]interface{}{}
	params["actors"] = actors
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.actor.getProfiles", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
