// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.actor.profile

import (
	appbskytypes "github.com/bluesky-social/indigo/api/bsky"
	"github.com/bluesky-social/indigo/lex/util"
)

// RECORDTYPE: ActorProfile
type ActorProfile struct {
	LexiconTypeID string `json:"$type,const=fm.teal.actor.profile" cborgen:"$type,const=fm.teal.actor.profile"`
	// avatar: Small image to be displayed next to posts from account. AKA, 'profile picture'
	Avatar *util.LexBlob `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// banner: Larger horizontal image to display behind profile view.
	Banner    *util.LexBlob `json:"banner,omitempty" cborgen:"banner,omitempty"`
	CreatedAt *string       `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// description: Free-form profile description text.
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	// descriptionFacets: Annotations of text in the profile description (mentions, URLs, hashtags, etc).
	DescriptionFacets []*appbskytypes.RichtextFacet `json:"descriptionFacets,omitempty" cborgen:"descriptionFacets,omitempty"`
	DisplayName       *string                       `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	// featuredItem: The user's most recent item featured on their profile.
	FeaturedItem *ActorProfile_FeaturedItem `json:"featuredItem,omitempty" cborgen:"featuredItem,omitempty"`
}

// ActorProfile_FeaturedItem is a "featuredItem" in the fm.teal.actor.profile schema.
type ActorProfile_FeaturedItem struct {
	// mbid: The MusicBrainz ID URI of the item, formatted as mbid:<uuid>
	Mbid string `json:"mbid" cborgen:"mbid"`
	// type: The type of the item. Must be a valid Musicbrainz type, e.g. album, track, recording, etc.
	Type string `json:"type" cborgen:"type"`
}

func init() {
	util.RegisterType("fm.teal.actor.profile", &ActorProfile{})
}
