// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

import "github.com/bluesky-social/indigo/lex/util"

// schema: fm.teal.alpha.actor.profileStatus

// RECORDTYPE: AlphaActorProfileStatus
type AlphaActorProfileStatus struct {
	LexiconTypeID string `json:"$type,const=fm.teal.alpha.actor.profileStatus" cborgen:"$type,const=fm.teal.alpha.actor.profileStatus"`
	// completedOnboarding: The onboarding completion status
	CompletedOnboarding string `json:"completedOnboarding" cborgen:"completedOnboarding"`
	// createdAt: The timestamp when this status was created
	CreatedAt *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// updatedAt: The timestamp when this status was last updated
	UpdatedAt *string `json:"updatedAt,omitempty" cborgen:"updatedAt,omitempty"`
}

func init() {
	util.RegisterType("fm.teal.alpha.actor.profileStatus", &AlphaActorProfileStatus{})
}
