// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.actor.getProfile

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// AlphaActorGetProfile_Output is the output of a fm.teal.alpha.actor.getProfile call.
type AlphaActorGetProfile_Output struct {
	Actor *AlphaActorDefs_ProfileView `json:"actor" cborgen:"actor"`
}

// AlphaActorGetProfile calls the XRPC method "fm.teal.alpha.actor.getProfile".
//
// actor: The author's DID
func AlphaActorGetProfile(ctx context.Context, c util.LexClient, actor string) (*AlphaActorGetProfile_Output, error) {
	var out AlphaActorGetProfile_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.alpha.actor.getProfile", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
