// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.actor.searchActors

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// ActorSearchActors_Output is the output of a fm.teal.actor.searchActors call.
type ActorSearchActors_Output struct {
	Actors []*ActorDefs_MiniProfileView `json:"actors" cborgen:"actors"`
	// cursor: Cursor for pagination
	Cursor *string `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
}

// ActorSearchActors calls the XRPC method "fm.teal.actor.searchActors".
//
// cursor: Cursor for pagination
// limit: The maximum number of actors to return
// q: The search query
func ActorSearchActors(ctx context.Context, c util.LexClient, cursor string, limit int64, q string) (*ActorSearchActors_Output, error) {
	var out ActorSearchActors_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["q"] = q
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.actor.searchActors", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
