// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.actor.defs

import (
	appbskytypes "github.com/bluesky-social/indigo/api/bsky"
)

// ActorDefs_MiniProfileView is a "miniProfileView" in the fm.teal.actor.defs schema.
type ActorDefs_MiniProfileView struct {
	// avatar: IPLD of the avatar
	Avatar *string `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// did: The decentralized identifier of the actor
	Did         *string `json:"did,omitempty" cborgen:"did,omitempty"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Handle      *string `json:"handle,omitempty" cborgen:"handle,omitempty"`
}

// ActorDefs_ProfileView is a "profileView" in the fm.teal.actor.defs schema.
type ActorDefs_ProfileView struct {
	// avatar: IPLD of the avatar
	Avatar *string `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// banner: IPLD of the banner image
	Banner    *string `json:"banner,omitempty" cborgen:"banner,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// description: Free-form profile description text.
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	// descriptionFacets: Annotations of text in the profile description (mentions, URLs, hashtags, etc). May be changed to another (backwards compatible) lexicon.
	DescriptionFacets []*appbskytypes.RichtextFacet `json:"descriptionFacets,omitempty" cborgen:"descriptionFacets,omitempty"`
	// did: The decentralized identifier of the actor
	Did         *string `json:"did,omitempty" cborgen:"did,omitempty"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	// featuredItem: The user's most recent item featured on their profile.
	FeaturedItem *ActorProfile_FeaturedItem `json:"featuredItem,omitempty" cborgen:"featuredItem,omitempty"`
	Status       *ActorDefs_StatusView      `json:"status,omitempty" cborgen:"status,omitempty"`
}

// ActorDefs_StatusView is a "statusView" in the fm.teal.actor.defs schema.
//
// A declaration of the status of the actor.
type ActorDefs_StatusView struct {
	// expiry: The unix timestamp of the expiry time of the item. If unavailable, default to 10 minutes past the start time.
	Expiry *string            `json:"expiry,omitempty" cborgen:"expiry,omitempty"`
	Item   *FeedDefs_PlayView `json:"item,omitempty" cborgen:"item,omitempty"`
	// time: The unix timestamp of when the item was recorded
	Time *string `json:"time,omitempty" cborgen:"time,omitempty"`
}
