// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.feed.getPlay

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// AlphaFeedGetPlay_Output is the output of a fm.teal.alpha.feed.getPlay call.
type AlphaFeedGetPlay_Output struct {
	Play *AlphaFeedDefs_PlayView `json:"play" cborgen:"play"`
}

// AlphaFeedGetPlay calls the XRPC method "fm.teal.alpha.feed.getPlay".
//
// authorDID: The author's DID for the play
// rkey: The record key of the play
func AlphaFeedGetPlay(ctx context.Context, c *xrpc.Client, authorDID string, rkey string) (*AlphaFeedGetPlay_Output, error) {
	var out AlphaFeedGetPlay_Output

	params := map[string]interface{}{
		"authorDID": authorDID,
		"rkey":      rkey,
	}
	if err := c.Do(ctx, xrpc.Query, "", "fm.teal.alpha.feed.getPlay", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
