// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.feed.defs

// AlphaFeedDefs_Artist is a "artist" in the fm.teal.alpha.feed.defs schema.
type AlphaFeedDefs_Artist struct {
	// artistMbId: The Musicbrainz ID of the artist
	ArtistMbId *string `json:"artistMbId,omitempty" cborgen:"artistMbId,omitempty"`
	// artistName: The name of the artist
	ArtistName string `json:"artistName" cborgen:"artistName"`
}

// AlphaFeedDefs_PlayView is a "playView" in the fm.teal.alpha.feed.defs schema.
type AlphaFeedDefs_PlayView struct {
	// artists: Array of artists in order of original appearance.
	Artists []*AlphaFeedDefs_Artist `json:"artists" cborgen:"artists"`
	// duration: The length of the track in seconds
	Duration *int64 `json:"duration,omitempty" cborgen:"duration,omitempty"`
	// isrc: The ISRC code associated with the recording
	Isrc *string `json:"isrc,omitempty" cborgen:"isrc,omitempty"`
	// musicServiceBaseDomain: The base domain of the music service. e.g. music.apple.com, tidal.com, spotify.com. Defaults to 'local' if not provided.
	MusicServiceBaseDomain *string `json:"musicServiceBaseDomain,omitempty" cborgen:"musicServiceBaseDomain,omitempty"`
	// originUrl: The URL associated with this track
	OriginUrl *string `json:"originUrl,omitempty" cborgen:"originUrl,omitempty"`
	// playedTime: The unix timestamp of when the track was played
	PlayedTime *string `json:"playedTime,omitempty" cborgen:"playedTime,omitempty"`
	// recordingMbId: The Musicbrainz recording ID of the track
	RecordingMbId *string `json:"recordingMbId,omitempty" cborgen:"recordingMbId,omitempty"`
	// releaseMbId: The Musicbrainz release ID
	ReleaseMbId *string `json:"releaseMbId,omitempty" cborgen:"releaseMbId,omitempty"`
	// releaseName: The name of the release/album
	ReleaseName *string `json:"releaseName,omitempty" cborgen:"releaseName,omitempty"`
	// submissionClientAgent: A user-agent style string specifying the user agent. e.g. tealtracker/0.0.1b (Linux; Android 13; SM-A715F). Defaults to 'manual/unknown' if not provided.
	SubmissionClientAgent *string `json:"submissionClientAgent,omitempty" cborgen:"submissionClientAgent,omitempty"`
	// trackMbId: The Musicbrainz ID of the track
	TrackMbId *string `json:"trackMbId,omitempty" cborgen:"trackMbId,omitempty"`
	// trackName: The name of the track
	TrackName string `json:"trackName" cborgen:"trackName"`
}
