// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

import "github.com/bluesky-social/indigo/lex/util"

// schema: fm.teal.feed.play

// RECORDTYPE: FeedPlay
type FeedPlay struct {
	LexiconTypeID string `json:"$type,const=fm.teal.feed.play" cborgen:"$type,const=fm.teal.feed.play"`
	// artistMbIds: DEPRECATED: USE 'artists' INSTEAD. Array of Musicbrainz artist IDs.
	ArtistMbIds []string `json:"artistMbIds,omitempty" cborgen:"artistMbIds,omitempty"`
	// artistNames: DEPRECATED: USE 'artists' INSTEAD. Array of artist names in order of original appearance.
	ArtistNames []string `json:"artistNames,omitempty" cborgen:"artistNames,omitempty"`
	// artists: Array of artists in order of original appearance.
	Artists []*FeedDefs_Artist `json:"artists,omitempty" cborgen:"artists,omitempty"`
	// duration: The length of the track in seconds
	Duration *int64 `json:"duration,omitempty" cborgen:"duration,omitempty"`
	// isrc: The ISRC code associated with the recording
	Isrc *string `json:"isrc,omitempty" cborgen:"isrc,omitempty"`
	// musicServiceBaseDomain: The base domain of the music service. e.g. music.apple.com, tidal.com, spotify.com. Defaults to 'local' if unavailable or not provided.
	MusicServiceBaseDomain *string `json:"musicServiceBaseDomain,omitempty" cborgen:"musicServiceBaseDomain,omitempty"`
	// originUrl: The URL associated with this track
	OriginUrl *string `json:"originUrl,omitempty" cborgen:"originUrl,omitempty"`
	// playedTime: The unix timestamp of when the track was played
	PlayedTime *string `json:"playedTime,omitempty" cborgen:"playedTime,omitempty"`
	// recordingMbId: The MusicBrainz recording ID URI of the track, formatted as mbid:<uuid>
	RecordingMbId *string `json:"recordingMbId,omitempty" cborgen:"recordingMbId,omitempty"`
	// releaseDiscriminant: Distinguishing information for release variants (e.g. 'Deluxe Edition', 'Remastered', '2023 Remaster', 'Special Edition'). Used to differentiate between different versions of the same base release while maintaining grouping capabilities.
	ReleaseDiscriminant *string `json:"releaseDiscriminant,omitempty" cborgen:"releaseDiscriminant,omitempty"`
	// releaseMbId: The MusicBrainz release ID URI, formatted as mbid:<uuid>
	ReleaseMbId *string `json:"releaseMbId,omitempty" cborgen:"releaseMbId,omitempty"`
	// releaseName: The name of the release/album
	ReleaseName *string `json:"releaseName,omitempty" cborgen:"releaseName,omitempty"`
	// submissionClientAgent: A metadata string specifying the user agent where the format is `<app-identifier>/<version> (<kernel/OS-base>; <platform/OS-version>; <device-model>)`. If string is provided, only `app-identifier` and `version` are required. `app-identifier` is recommended to be in reverse dns format. Defaults to 'manual/unknown' if unavailable or not provided.
	SubmissionClientAgent *string `json:"submissionClientAgent,omitempty" cborgen:"submissionClientAgent,omitempty"`
	// trackDiscriminant: Distinguishing information for track variants (e.g. 'Acoustic Version', 'Live at Wembley', 'Radio Edit', 'Demo'). Used to differentiate between different versions of the same base track while maintaining grouping capabilities.
	TrackDiscriminant *string `json:"trackDiscriminant,omitempty" cborgen:"trackDiscriminant,omitempty"`
	// trackMbId: The MusicBrainz ID URI of the track, formatted as mbid:<uuid>
	TrackMbId *string `json:"trackMbId,omitempty" cborgen:"trackMbId,omitempty"`
	// trackName: The name of the track
	TrackName string `json:"trackName" cborgen:"trackName"`
}

func init() {
	util.RegisterType("fm.teal.feed.play", &FeedPlay{})
}
