// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.feed.getPlay

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// FeedGetPlay_Output is the output of a fm.teal.feed.getPlay call.
type FeedGetPlay_Output struct {
	Play *FeedDefs_PlayView `json:"play" cborgen:"play"`
}

// FeedGetPlay calls the XRPC method "fm.teal.feed.getPlay".
//
// authorDID: The author's DID for the play
// rkey: The record key of the play
func FeedGetPlay(ctx context.Context, c util.LexClient, authorDID string, rkey string) (*FeedGetPlay_Output, error) {
	var out FeedGetPlay_Output

	params := map[string]interface{}{}
	params["authorDID"] = authorDID
	params["rkey"] = rkey
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.feed.getPlay", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
