// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.feed.getActorFeed

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// FeedGetActorFeed_Output is the output of a fm.teal.feed.getActorFeed call.
type FeedGetActorFeed_Output struct {
	Plays []*FeedDefs_PlayView `json:"plays" cborgen:"plays"`
}

// FeedGetActorFeed calls the XRPC method "fm.teal.feed.getActorFeed".
//
// authorDID: The author's DID for the play
// cursor: The cursor to start the query from
// limit: The upper limit of tracks to get per request. Default is 20, max is 50.
func FeedGetActorFeed(ctx context.Context, c util.LexClient, authorDID string, cursor string, limit int64) (*FeedGetActorFeed_Output, error) {
	var out FeedGetActorFeed_Output

	params := map[string]interface{}{}
	params["authorDID"] = authorDID
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.feed.getActorFeed", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
