// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.feed.defs

// FeedDefs_Artist is a "artist" in the fm.teal.feed.defs schema.
type FeedDefs_Artist struct {
	// artistMbId: The MusicBrainz artist ID URI, formatted as mbid:<uuid>
	ArtistMbId *string `json:"artistMbId,omitempty" cborgen:"artistMbId,omitempty"`
	// artistName: The name of the artist
	ArtistName string `json:"artistName" cborgen:"artistName"`
}

// FeedDefs_PlayView is a "playView" in the fm.teal.feed.defs schema.
type FeedDefs_PlayView struct {
	// artists: Array of artists in order of original appearance.
	Artists []*FeedDefs_Artist `json:"artists" cborgen:"artists"`
	// duration: The length of the track in seconds
	Duration *int64 `json:"duration,omitempty" cborgen:"duration,omitempty"`
	// isrc: The ISRC code associated with the recording
	Isrc *string `json:"isrc,omitempty" cborgen:"isrc,omitempty"`
	// musicServiceUri: The canonical URI identifying the listening surface or music service.
	MusicServiceUri *string `json:"musicServiceUri,omitempty" cborgen:"musicServiceUri,omitempty"`
	// originUri: The exact URI where the listening event originated.
	OriginUri *string `json:"originUri,omitempty" cborgen:"originUri,omitempty"`
	// playedTime: The datetime at which playback began.
	PlayedTime *string `json:"playedTime,omitempty" cborgen:"playedTime,omitempty"`
	// recordingMbId: The MusicBrainz recording ID URI of the track, formatted as mbid:<uuid>
	RecordingMbId *string `json:"recordingMbId,omitempty" cborgen:"recordingMbId,omitempty"`
	// releaseMbId: The MusicBrainz release ID URI, formatted as mbid:<uuid>
	ReleaseMbId *string `json:"releaseMbId,omitempty" cborgen:"releaseMbId,omitempty"`
	// releaseName: The name of the release/album
	ReleaseName *string `json:"releaseName,omitempty" cborgen:"releaseName,omitempty"`
	// submissionClientAgent: A user-agent style string specifying the user agent. e.g. tealtracker/0.0.1b (Linux; Android 13; SM-A715F). Defaults to 'manual/unknown' if not provided.
	SubmissionClientAgent *string `json:"submissionClientAgent,omitempty" cborgen:"submissionClientAgent,omitempty"`
	// trackMbId: The MusicBrainz ID URI of the track, formatted as mbid:<uuid>
	TrackMbId *string `json:"trackMbId,omitempty" cborgen:"trackMbId,omitempty"`
	// trackName: The name of the track
	TrackName string `json:"trackName" cborgen:"trackName"`
}
