// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.stats.getUserTopReleases

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// AlphaStatsGetUserTopReleases_Output is the output of a fm.teal.alpha.stats.getUserTopReleases call.
type AlphaStatsGetUserTopReleases_Output struct {
	// cursor: Next page cursor
	Cursor   *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Releases []*AlphaStatsDefs_ReleaseView `json:"releases" cborgen:"releases"`
}

// AlphaStatsGetUserTopReleases calls the XRPC method "fm.teal.alpha.stats.getUserTopReleases".
//
// actor: The user's DID or handle
// cursor: Pagination cursor
// limit: Number of releases to return
// period: Time period for top releases
func AlphaStatsGetUserTopReleases(ctx context.Context, c util.LexClient, actor string, cursor string, limit int64, period string) (*AlphaStatsGetUserTopReleases_Output, error) {
	var out AlphaStatsGetUserTopReleases_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if period != "" {
		params["period"] = period
	}
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.alpha.stats.getUserTopReleases", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
