// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.stats.defs

// AlphaStatsDefs_ArtistView is a "artistView" in the fm.teal.alpha.stats.defs schema.
type AlphaStatsDefs_ArtistView struct {
	// mbid: MusicBrainz artist ID URI, formatted as mbid:<uuid>
	Mbid *string `json:"mbid,omitempty" cborgen:"mbid,omitempty"`
	// name: Artist name
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// playCount: Total number of plays for this artist
	PlayCount *int64 `json:"playCount,omitempty" cborgen:"playCount,omitempty"`
}

// AlphaStatsDefs_RecordingView is a "recordingView" in the fm.teal.alpha.stats.defs schema.
type AlphaStatsDefs_RecordingView struct {
	// mbid: MusicBrainz recording ID URI, formatted as mbid:<uuid>
	Mbid *string `json:"mbid,omitempty" cborgen:"mbid,omitempty"`
	// name: Recording/track name
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// playCount: Total number of plays for this recording
	PlayCount *int64 `json:"playCount,omitempty" cborgen:"playCount,omitempty"`
}

// AlphaStatsDefs_ReleaseView is a "releaseView" in the fm.teal.alpha.stats.defs schema.
type AlphaStatsDefs_ReleaseView struct {
	// mbid: MusicBrainz release ID URI, formatted as mbid:<uuid>
	Mbid *string `json:"mbid,omitempty" cborgen:"mbid,omitempty"`
	// name: Release/album name
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// playCount: Total number of plays for this release
	PlayCount *int64 `json:"playCount,omitempty" cborgen:"playCount,omitempty"`
}
