// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.stats.getTopArtists

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// AlphaStatsGetTopArtists_Output is the output of a fm.teal.alpha.stats.getTopArtists call.
type AlphaStatsGetTopArtists_Output struct {
	Artists []*AlphaStatsDefs_ArtistView `json:"artists" cborgen:"artists"`
	// cursor: Next page cursor
	Cursor *string `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
}

// AlphaStatsGetTopArtists calls the XRPC method "fm.teal.alpha.stats.getTopArtists".
//
// cursor: Pagination cursor
// limit: Number of artists to return
// period: Time period for top artists
func AlphaStatsGetTopArtists(ctx context.Context, c util.LexClient, cursor string, limit int64, period string) (*AlphaStatsGetTopArtists_Output, error) {
	var out AlphaStatsGetTopArtists_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if period != "" {
		params["period"] = period
	}
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.alpha.stats.getTopArtists", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
