// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.stats.getTopReleases

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// AlphaStatsGetTopReleases_Output is the output of a fm.teal.alpha.stats.getTopReleases call.
type AlphaStatsGetTopReleases_Output struct {
	// cursor: Next page cursor
	Cursor   *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Releases []*AlphaStatsDefs_ReleaseView `json:"releases" cborgen:"releases"`
}

// AlphaStatsGetTopReleases calls the XRPC method "fm.teal.alpha.stats.getTopReleases".
//
// cursor: Pagination cursor
// limit: Number of releases to return
// period: Time period for top releases
func AlphaStatsGetTopReleases(ctx context.Context, c util.LexClient, cursor string, limit int64, period string) (*AlphaStatsGetTopReleases_Output, error) {
	var out AlphaStatsGetTopReleases_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if period != "" {
		params["period"] = period
	}
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.alpha.stats.getTopReleases", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
