// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.stats.getUserTopArtists

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// AlphaStatsGetUserTopArtists_Output is the output of a fm.teal.alpha.stats.getUserTopArtists call.
type AlphaStatsGetUserTopArtists_Output struct {
	Artists []*AlphaStatsDefs_ArtistView `json:"artists" cborgen:"artists"`
	// cursor: Next page cursor
	Cursor *string `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
}

// AlphaStatsGetUserTopArtists calls the XRPC method "fm.teal.alpha.stats.getUserTopArtists".
//
// actor: The user's DID or handle
// cursor: Pagination cursor
// limit: Number of artists to return
// period: Time period for top artists
func AlphaStatsGetUserTopArtists(ctx context.Context, c util.LexClient, actor string, cursor string, limit int64, period string) (*AlphaStatsGetUserTopArtists_Output, error) {
	var out AlphaStatsGetUserTopArtists_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if period != "" {
		params["period"] = period
	}
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.alpha.stats.getUserTopArtists", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
