// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package teal

// schema: fm.teal.alpha.stats.getLatest

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// AlphaStatsGetLatest_Output is the output of a fm.teal.alpha.stats.getLatest call.
type AlphaStatsGetLatest_Output struct {
	Plays []*AlphaFeedDefs_PlayView `json:"plays" cborgen:"plays"`
}

// AlphaStatsGetLatest calls the XRPC method "fm.teal.alpha.stats.getLatest".
//
// limit: Number of latest plays to return
func AlphaStatsGetLatest(ctx context.Context, c util.LexClient, limit int64) (*AlphaStatsGetLatest_Output, error) {
	var out AlphaStatsGetLatest_Output

	params := map[string]interface{}{}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "fm.teal.alpha.stats.getLatest", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
