// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.bsky.actor.declaration

func init() {
	// util.RegisterType("chat.bsky.actor.declaration", &ActorDeclaration{})
} //
// RECORDTYPE: ActorDeclaration
type ActorDeclaration struct {
	LexiconTypeID string `json:"$type,const=chat.bsky.actor.declaration" cborgen:"$type,const=chat.bsky.actor.declaration"`
	AllowIncoming string `json:"allowIncoming" cborgen:"allowIncoming"`
}
