package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/bluesky-social/indigo/lex"
	"golang.org/x/tools/imports"
)

type moduleConfig struct {
	dir        string
	importPath string
	pkgName    string
	cborOut    string
	cborTypes  []string
}

var modules = []moduleConfig{
	{
		dir:        "./api/bsky",
		importPath: "github.com/teal-fm/piper/api/bsky",
		pkgName:    "bsky",
	},
	{
		dir:        "./api/teal",
		importPath: "github.com/teal-fm/piper/api/teal",
		pkgName:    "teal",
		cborOut:    "api/teal/cbor_gen.go",
		cborTypes: []string{
			"teal.AlphaFeedPlay",
			"teal.AlphaActorProfile",
			"teal.AlphaActorStatus",
			"teal.AlphaActorProfile_FeaturedItem",
			"teal.AlphaFeedDefs_PlayView",
			"teal.AlphaFeedDefs_Artist",
		},
	},
}

var cborRunnerTpl = template.Must(template.New("runner").Parse(`//go:build ignore

package main

import (
	"{{.ImportPath}}"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func main() {
	genCfg := cbg.Gen{
		MaxStringLength: 1_000_000,
	}

	err := genCfg.WriteMapEncodersToFile(
		"{{.CborOut}}",
		"{{.PkgName}}",
		{{- range .CborTypes }}
		{{.}}{},
		{{- end }}
	)
	if err != nil {
		panic(err)
	}
}
`))

func main() {
	if err := generateLexicons(); err != nil {
		log.Fatalf("Fatal error generating lexicons: %v", err)
	}
}

func generateLexicons() error {
	if err := os.RemoveAll("./api"); err != nil {
		return fmt.Errorf("removing api dir: %w", err)
	}

	if err := generateLex("./lexcfg.json", "./lexicons"); err != nil {
		return fmt.Errorf("generating lex: %w", err)
	}

	for _, mod := range modules {
		if err := processModule(mod); err != nil {
			return fmt.Errorf("processing module %s: %w", mod.pkgName, err)
		}
	}

	return nil
}

func processModule(mod moduleConfig) error {
	savedInits, err := stripMethods(mod.dir)
	if err != nil {
		return fmt.Errorf("stripping methods: %w", err)
	}

	if err := fixImports(mod.dir); err != nil {
		return fmt.Errorf("fixing imports: %w", err)
	}

	if len(mod.cborTypes) > 0 {
		if err := generateCBOR(mod); err != nil {
			return fmt.Errorf("generating CBOR: %w", err)
		}
	}

	if len(savedInits) > 0 {
		if err := restoreInits(savedInits); err != nil {
			return fmt.Errorf("restoring init functions: %w", err)
		}

		// Re-run fixImports to restore any dependencies (like lexutil)
		// that the init functions might require to compile properly.
		if err := fixImports(mod.dir); err != nil {
			return fmt.Errorf("fixing imports post-restore: %w", err)
		}
	}

	return nil
}

func generateLex(lexcfgPath, lexiconsPath string) error {
	configData, err := os.ReadFile(lexcfgPath)
	if err != nil {
		return fmt.Errorf("reading config: %w", err)
	}

	packages, err := lex.ParsePackages(configData)
	if err != nil {
		return fmt.Errorf("parsing config: %w", err)
	}

	schemas, err := loadSchemas(lexiconsPath)
	if err != nil {
		return err
	}

	if err := lex.Run(schemas, nil, packages); err != nil {
		return fmt.Errorf("generating code: %w", err)
	}

	return nil
}

func loadSchemas(lexiconsPath string) ([]*lex.Schema, error) {
	var schemas []*lex.Schema

	err := filepath.WalkDir(lexiconsPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".json") {
			return nil
		}

		s, err := lex.ReadSchema(path)
		if err != nil {
			return fmt.Errorf("reading schema %s: %w", path, err)
		}

		schemas = append(schemas, s)
		return nil
	})

	return schemas, err
}

// stripMethods walks the AST to remove MarshalCBOR, and UnmarshalCBOR
// methods generated by lex so cbor-gen can generate highly optimized versions.
// It simultaneously saves and returns `init` functions to be restored later.
func stripMethods(root string) (map[string][]ast.Decl, error) {
	files, err := filepath.Glob(filepath.Join(root, "*.go"))
	if err != nil {
		return nil, fmt.Errorf("getting go files: %w", err)
	}

	fset := token.NewFileSet()
	savedInits := make(map[string][]ast.Decl)

	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", file, err)
		}

		node, err := parser.ParseFile(fset, file, content, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parsing %s: %w", file, err)
		}

		var keep []ast.Decl
		var inits []ast.Decl
		modified := false

		for _, decl := range node.Decls {
			if fn, ok := decl.(*ast.FuncDecl); ok {
				name := fn.Name.Name
				if name == "init" {
					inits = append(inits, decl)
					modified = true
					continue
				}
				if name == "MarshalCBOR" || name == "UnmarshalCBOR" {
					modified = true
					continue // Strip these methods entirely
				}
			}
			keep = append(keep, decl)
		}

		// Avoid unnecessary writes if nothing changed
		if !modified {
			continue
		}

		if len(inits) > 0 {
			savedInits[file] = inits
		}

		node.Decls = keep

		// Write safely to an in-memory buffer before flushing to file
		var buf bytes.Buffer
		if err := printer.Fprint(&buf, fset, node); err != nil {
			return nil, fmt.Errorf("printing %s: %w", file, err)
		}

		if err := os.WriteFile(file, buf.Bytes(), 0644); err != nil {
			return nil, fmt.Errorf("writing modified %s: %w", file, err)
		}
	}

	return savedInits, nil
}

// restoreInits takes the mapped init declarations and appends them back
// to their respective files via AST.
func restoreInits(saved map[string][]ast.Decl) error {
	fset := token.NewFileSet()

	for file, inits := range saved {
		content, err := os.ReadFile(file)
		if err != nil {
			return fmt.Errorf("reading %s: %w", file, err)
		}

		node, err := parser.ParseFile(fset, file, content, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parsing %s: %w", file, err)
		}

		// Append the saved init functions back to the AST declarations
		node.Decls = append(node.Decls, inits...)

		var buf bytes.Buffer
		if err := printer.Fprint(&buf, fset, node); err != nil {
			return fmt.Errorf("printing %s: %w", file, err)
		}

		if err := os.WriteFile(file, buf.Bytes(), 0644); err != nil {
			return fmt.Errorf("writing restored %s: %w", file, err)
		}
	}

	return nil
}

func fixImports(root string) error {
	files, err := filepath.Glob(filepath.Join(root, "*.go"))
	if err != nil {
		return fmt.Errorf("getting go files: %w", err)
	}

	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			return fmt.Errorf("reading %s: %w", file, err)
		}

		formatted, err := imports.Process(file, data, nil)
		if err != nil {
			return fmt.Errorf("formatting imports in %s: %w", file, err)
		}

		if err := os.WriteFile(file, formatted, 0644); err != nil {
			return fmt.Errorf("writing fixed imports %s: %w", file, err)
		}
	}

	return nil
}

func generateCBOR(mod moduleConfig) error {
	// Generate the runner locally so it hooks into the project's go.mod
	runnerName := fmt.Sprintf("gencbor_%s_tmp.go", mod.pkgName)

	f, err := os.Create(runnerName)
	if err != nil {
		return fmt.Errorf("failed to create runner file: %w", err)
	}

	err = cborRunnerTpl.Execute(f, map[string]any{
		"ImportPath": mod.importPath,
		"PkgName":    mod.pkgName,
		"CborOut":    mod.cborOut,
		"CborTypes":  mod.cborTypes,
	})
	f.Close()

	if err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Clean up the transient runner once we're done
	defer os.Remove(runnerName)

	cmd := exec.Command("go", "run", runnerName)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to run CBOR generator: %w", err)
	}

	return nil
}
